version: '3.8'
services:
  dapr-placement:
    image: "daprio/dapr:latest"
    container_name: "dapr-placement"
    ports:
      - "50005:50005"
    command: ["./placement"]
    networks:
      - dapr-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    environment:
      - DAPR_HTTP_PORT=3500
      - BACKEND_APP_ID=backend
    depends_on:
      - backend
      - dapr-placement
    command: ["dapr", "run", "--app-id", "frontend", "--app-port", "8000", "--", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - dapr-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DAPR_HTTP_PORT=3500
    depends_on:
      - dapr-placement
    command: ["dapr", "run", "--app-id", "backend", "--app-port", "4000", "--", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "4000"]
    networks:
      - dapr-network

networks:
  dapr-network:
    driver: bridge
