apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "frontend"
        dapr.io/app-port: "8000"
        dapr.io/log-level: "debug"  # Optional: Set log level for Dapr
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        ports:
        - containerPort: 8000
        command: ["python3", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
        env:
        - name: BACKEND_APP_ID
          value: "backend"
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: DAPR_GRPC_PORT
          value: "50001"
