apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sample-cron
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 10s"
    - name: payload
      value: "Hello, world!"
