name: Trigger auto deployment for public-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/public-app-AutoDeployTrigger-6e2417bb-327a-4ae7-b0db-146636c1a686.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PUBLICAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PUBLICAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PUBLICAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.PUBLICAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PUBLICAPP_REGISTRY_PASSWORD }}
          containerAppName: public-app
          resourceGroup: on-poc
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


